### ISSUE TITLE
Ghostscript

### ISSUE THREAD

**Issue by 1337g** [TheKingOfDuck/S2-057#10]
大家检查下 有没有用 ghostscript传马

**Comment by TheKingOfDuck** [comment]
就你这智商 可以回家睡觉了

**Comment by Anonymous-ghost** [comment]
大佬你以为学个python就很牛逼么，你以为把python弄成二进制格式编译了就很安全。忘了说了你的代码昨天被爆菊了。今天和你说一下。python反编译了解一下。十六进制转中文了解一下。我用c#模仿了一下你的程序。你的程序写的是真垃圾只能2.7我3.6于是我写了一个所有.net环境全部能运行的你的辣鸡程序。顺便复习了一下十六进制转中文的代码

**Comment by TheKingOfDuck** [comment]
你是真的弱智 什么叫代码被爆菊花 他妈的本来就是写来娱乐的 避免一下子被看到代码内容就编译了一下 你他妈还3.6 放你妈屁  老子pycharm就是3.6的python 系统是2.7的版本 都测试过的  你他妈傻逼

**Comment by TheKingOfDuck** [comment]
我的联系方式在readme里面写的有 来加我

**Comment by Anonymous-ghost** [comment]
我的意思是你就会个python牛逼个鸡巴。。。意思你还会汇编语言。。。。。你用汇编给我写个exp放出来娱乐一下。我是不会大佬牛逼写一个娱乐一下呗

**Comment by Anonymous-ghost** [comment]
你这种渣渣加你能学到什么东西。。。。。。。

**Comment by TheKingOfDuck** [comment]
来 发给联系方式给我

**Comment by chaos-cl** [comment]
有些人就是没有一点娱乐精神。

**Comment by TheKingOfDuck** [comment]
“我用c#模仿了一下你的程序”  模仿你mmp啊 这个就说明了你是个傻逼 什么exp 老子本来就是就是为了娱乐 皮一下 很开心 你他妈给我扯到什么汇编语言去了。BigSB！！！

**Comment by 1337g** [comment]
… 淡定兄弟 我只是觉得 装有问题的库然后只为了恶搞下挺可疑的

**Comment by TheKingOfDuck** [comment]
@1337g 老兄抱歉 有这种态度是好的  主要是为了骂 @Anonymous-ghost 这个傻逼

**Comment by Anonymous-ghost** [comment]
技术牛逼了在放出来东西娱乐。。。一个python开源的你娱乐一下。你用汇编写一个娱乐娱乐。这样你的娱乐水平更高。。。。。哟要不我用公钥加密我的联系方式。。你来破译一下加我呗大佬

**Comment by TheKingOfDuck** [comment]
@Anonymous-ghost 去你妈的再说一遍 这他妈不是汇编  就是普通的编译一下
执行
`python -m py_compile Main.py`
就编译生成了Main.pyc

你是弱智么？不 你就是弱智 有本事bb 有本事就发你的联系方式过来 破解你麻痹  老子在readme里面写的清清楚楚 弱智！

**Comment by Anonymous-ghost** [comment]
也娱乐娱乐别人。。。。。会点编程语言就娱乐下别人。。。你是真辣鸡。。

**Comment by Anonymous-ghost** [comment]
对了你的联系方式是自己写的加密方式口算md5 单手破解私钥加密？？？？ 小弟破解不了啊。像我这种我只会输出hello helloword 的人怎么可能知道大佬你的建议方式啊。。吓死我了
